name: "Update repositories.json"

on:
  workflow_dispatch:
  schedule:
    - cron: "00 01 1 * *"

jobs:
  update-repositories:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: repositories
          key: v2-${{ hashFiles('repositories.json') }}

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Install Dependencies
        run: yarn

      - name: Run update-repositories.mjs
        run: node ./scripts/update-repositories.mjs

      - name: Run tests
        run: yarn execute "RUN https://pkg.pr.new/prettier/prettier@main VS latest"

      - uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Update repositories.json"
          branch: automated-update-repositories
          branch-suffix: timestamp
          title: "Update repositories.json"
